# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-20 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20171220_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestDetail', models.CharField(max_length=1000)),
            ],
        ),
    ]
