# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-20 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_requestme'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='link',
            field=models.CharField(default='1', max_length=1000),
            preserve_default=False,
        ),
    ]
