# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20171220_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestme',
            name='name',
            field=models.CharField(default='saurabh', max_length=100),
            preserve_default=False,
        ),
    ]
