# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_20171221_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesimage',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
