# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20171221_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
