# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-22 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20171221_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestme',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
