# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-22 18:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_requestme_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestme',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
